<a href="https://colab.research.google.com/github/Prabhjeet18/Models_Saving_Using_Pickle_And_JobLib/blob/main/Save_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing Necessary Libraries

In [27]:
import pandas as pd
import numpy as np
from sklearn import linear_model

##Importing Dataset

In [28]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

## Importing And Training Model

In [29]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [30]:
model.coef_

array([135.78767123])

In [31]:
model.intercept_

180616.43835616432

In [32]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

## Saving Model Using Pickle Module

In [33]:
import pickle

In [34]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

In [ ]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [35]:
mp.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

## Saving Model Using SkLearn JobLib

In [37]:
import joblib

In [38]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [39]:
mj = joblib.load('model_joblib')

In [40]:
mj.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])